services:
  webnas:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /:/host_root
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    networks:
      - nas-network
    restart: unless-stopped

  webssh:
    build: ./webssh
    ports:
    - "8888:8888"
    networks:
      - nas-network
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "5491:5491"
    volumes:
      - ./CaddyFile:/etc/caddy/Caddyfile
    networks:
      - nas-network
    depends_on:
      - nextjs

networks:
  nas-network:
    driver: bridge
