services:
  nextjs:
    container_name: web-nas
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /:/host_root
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    networks:
      - nas-network
    restart: unless-stopped
    depends_on:
      - novnc

  caddy:
    image: caddy:alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "6081:6081"
      - "5491:5491"
    volumes:
      - ./CaddyFile:/etc/caddy/Caddyfile
    networks:
      - nas-network
    depends_on:
      - nextjs

  # 86x_64x/AMD
  # novnc:
  #   image: theasp/novnc:latest
  #   env_file:
  #     - ./noVNC.env
  #   environment:
  #     - DISPLAY_WIDTH=1920
  #     - DISPLAY_HEIGHT=1080
  #     - RUN_XTERM=yes
  #     - RUN_FLUXBOX=no
  #   ports:
  #     - "6081:8080"
  #   restart: unless-stopped
  #   networks:
  #     - nas-network

  # ARM
  novnc:
    image: 11notes/novnc:stable
    container_name: novnc-kasm
    privileged: true
    env_file:
    - ./noVNC.env
    environment:
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
      - RUN_XTERM=yes
      - RUN_FLUXBOX=yes
      - TZ=Asia/Bangkok
      - TITLE=MyNAS-Desktop
      # - CUSTOM_USER=admin
      # - PASSWORD=secretpassword
    volumes:
      - ./webtop_data:/config
      - /:/host_root
    devices:
      - /dev/dri:/dev/dri
    # ports:
    #   - "6081:3000"
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - nas-network

networks:
  nas-network:
    driver: bridge
