services:
  nextjs:
    container_name: web-nas
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    networks:
      - nas-network
    depends_on:
      - novnc

  caddy:
    image: caddy:alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "5491:5491"
    volumes:
      - ./CaddyFile:/etc/caddy/Caddyfile
    networks:
      - nas-network
    depends_on:
      - nextjs

  novnc:
    image: theasp/novnc:latest
    env_file:
      - ./noVNC.env
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=yes
      - RUN_FLUXBOX=no
    ports:
      - "6081:8080"
    networks:
      - nas-network

networks:
  nas-network:
    driver: bridge
